NDefines.NGraphics.BORDER_COLOR_SELECTION_STATE_R = 0.35
NDefines.NGraphics.BORDER_COLOR_SELECTION_STATE_G = 0.75
NDefines.NGraphics.BORDER_COLOR_SELECTION_STATE_B = 0.75
NDefines.NGraphics.BORDER_COLOR_SELECTION_PROVINCE_R = 0.15
NDefines.NGraphics.BORDER_COLOR_SELECTION_PROVINCE_G = 0.9
NDefines.NGraphics.BORDER_COLOR_SELECTION_PROVINCE_B = 0.9